defaults:
  - reward: base
env_name: SuperMarioBros-v0
complex_movement: True
num_skip_frames: 4
num_stack_frames: 3
clip_top: 0
clip_bot: 0
clip_left: 0
clip_right: 0
width: 256
height: 240
grayscale: True