"""
This type stub file was generated by pyright.
"""

from .smb_env import SuperMarioBrosEnv
from .smb_random_stages_env import SuperMarioBrosRandomStagesEnv
from ._registration import make

"""Registration code of Gym environments in this package."""
__all__ = [make.__name__, SuperMarioBrosEnv.__name__, SuperMarioBrosRandomStagesEnv.__name__]
