"""
This type stub file was generated by pyright.
"""

"""Static action sets for binary to discrete action space wrappers."""
from typing import List

RIGHT_ONLY: List[List[str]] = ...
SIMPLE_MOVEMENT: List[List[str]] = ...
COMPLEX_MOVEMENT: List[List[str]] = ...
