"""
This type stub file was generated by pyright.
"""

import numpy as np
from nes_py import NESEnv

"""An OpenAI Gym environment for Super Mario Bros. and Lost Levels."""
_STATUS_MAP = ...
_BUSY_STATES = ...
_ENEMY_TYPE_ADDRESSES = ...
_STAGE_OVER_ENEMIES = np.array([45, 49])
class SuperMarioBrosEnv(NESEnv):
    """An environment for playing Super Mario Bros with OpenAI Gym."""
    reward_range = ...
    def __init__(self, rom_mode=..., lost_levels=..., target=...) -> None:
        """
        Initialize a new Super Mario Bros environment.

        Args:
            rom_mode (str): the ROM mode to use when loading ROMs from disk
            lost_levels (bool): whether to load the ROM with lost levels.
                - False: load original Super Mario Bros.
                - True: load Super Mario Bros. Lost Levels
            target (tuple): a tuple of the (world, stage) to play as a level

        Returns:
            None

        """
        ...
    
    @property
    def is_single_stage_env(self): # -> bool:
        """Return True if this environment is a stage environment."""
        ...
    


__all__ = [SuperMarioBrosEnv.__name__]
