defaults:
  - agent: ppo
  - environment: subsampled
  - override /agent/learning_rate: constant
  - _self_

agent:
  learning_rate:
    config:
      initial_learning_rate: 4e-04
steps_per_update: 128