defaults:
  - agent: ppo
  - environment: subsampled
  - _self_

level: "1-1"
num_workers: 64
num_iters: 2000
steps_per_iter: 128
save_frequency: 50
experiment_name: "${environment.description}_${agent.description}"