defaults:
  - agent: ppo
  - environment: subsampled
  - override /agent/learning_rate: exponential_decay
  - _self_

experiment_name: "exp-dec_${agent.learning_rate.config.initial_learning_rate}_2e-06_step-1024"
num_workers: 8
num_updates: 1_000
steps_per_update: 128