defaults:
  - agent: ppo
  - environment: subsampled
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - _self_

_target_: config.main_config.NeurioConfig
level: "1-1"
num_workers: 32
num_iters: 500
steps_per_iter: 128
save_frequency: 50
render: False

agent:
  total_updates: ${num_iters}

  learning_rate:
    decay_iters: ${num_iters}

#hydra:
#  sweeper:
#    # ToDo: Add pruner as soon as it's available in the optuna sweeper
#    sampler:
#      n_startup_trials: 10
#    direction: maximize
#    study_name: Neurio-lev-${level}
#    storage: sqlite:///optuna_studies/${hydra.sweeper.study_name}.db
#    n_trials: 1
#    n_jobs: 1
#
#    params:
#      agent.learning_rate.learning_rate: tag(log, interval(0.0002, 0.0009))
#      agent.exp_buffer_size: choice(128, 256)
#      agent.batch_size: choice(64, 128, 256, 512)
#      agent.max_entropy_loss_weight: tag(log, interval(0.0001, 0.01))
#      agent.gamma: interval(0.8, 1.0)
#      agent.tau: interval(0.8, 1.0)
