defaults:
  - agent: ppo
  - environment: subsampled
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - _self_

_target_: src.config.main_config.NeurioConfig
level: "1-1"
num_workers: 32
num_iters: 1500
steps_per_iter: 128
save_frequency: 50

hydra:
  sweeper:
    # ToDo: Add pruner as soon as it's available in the optuna sweeper
    sampler:
      seed: 123
      n_startup_trials: 10
    direction: maximize
    study_name: Neurio-${level}
    storage: sqlite:///optuna_studies/${hydra.sweeper.study_name}.db
    n_trials: 3
    n_jobs: 1

    params:
      agent.learning_rate.learning_rate: tag(log, interval(0.0001, 0.001))
      agent.model.num_layers: range(3, 4)
      agent.model.num_filters: choice(16, 32, 64, 128, 256)
      agent.model.kernel_size: range(3, 5)
      agent.model.fc_size: range(100, 700)
      agent.critic_loss_weight: interval(0.5, 1.5)
      agent.entropy_loss_weight: tag(log, interval(0.0001, 0.01))
      agent.gamma: interval(0.5, 1.0)
      agent.tau: interval(0.5, 1.0)
