"""
This type stub file was generated by pyright.
"""

from .decode_target import decode_target
from .rom_path import rom_path

"""Methods for ROM file management."""
__all__ = [decode_target.__name__, rom_path.__name__]
