"""
This type stub file was generated by pyright.
"""

"""A method to decode target values for a ROM stage environment."""
def decode_target(target, lost_levels): # -> tuple[None, None, None] | tuple[int, int, int] | None:
    """
    Return the target area for target world and target stage.

    Args:
        target_world (None, int): the world to target
        target_stage (None, int): the stage to target
        lost_levels (bool): whether to use lost levels game

    Returns (int):
        the area to target to load the target world and stage

    """
    ...

__all__ = [decode_target.__name__]
