"""
This type stub file was generated by pyright.
"""

"""A method to load a ROM path."""
_ROM_PATHS = ...
def rom_path(lost_levels, rom_mode): # -> str:
    """
    Return the ROM filename for a game and ROM mode.

    Args:
        lost_levels (bool): whether to use the lost levels ROM
        rom_mode (str): the mode of the ROM hack to use as one of:
            - 'vanilla'
            - 'pixel'
            - 'downsample'
            - 'vanilla'

    Returns (str):
        the ROM path based on the input parameters

    """
    ...

__all__ = [rom_path.__name__]
