defaults:
  - model: actor_critic
  - learning_rate: linear_decay
  - _self_

_target_: src.config.agent.PPOAgentConfig

gamma: 0.99
tau: 0.95
epochs_per_update: 4
batch_size: 256
clip_param: 0.2
clip_value: False
critic_loss_weight: 0.5
entropy_loss_weight: 0.001
grad_clip_norm: 0.5
