defaults:
  - model: actor_critic
  - learning_rate: linear_decay
  - _self_

name: ppo
gamma: 0.99
gae_lambda: 0.95
epochs_per_update: 4
batch_size: 32
optimizer_epsilon: 1e-05
clip_param: 0.2
num_input_frames: 2
critic_loss_weight: 0.5
entropy_loss_weight: 0.001
grad_clip_norm: 0.5